services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bank
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: back
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://admin:admin@db:3306/bank"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend  # Only mount backend for local changes

volumes:
  db_data:
