services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bank
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/import:/docker-entrypoint-initdb.d #Importa el sql
  backend:
    build: .
    container_name: back
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://admin:admin@db:3306/bank"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # Mount the entire project directory
volumes:
  db_data: